- README.md
- bin/init.bash
- config/flavors/all-test.yml
- config/flavors/k8s-cluster-test.yml
The test flavor is broken and we dont need it anymore -> remove it. 
https://github.com/elastisys/compliantkubernetes-kubespray/issues/12
> Removed test flavor

- .gitignore
- .mdl_style.rb
- .mdlrc
- .pre-commit-config.yaml
- README.md
- bin/apply.bash
- bin/ck8s-kubespray
- bin/common.bash
- bin/init.bash
- bin/run-playbook.bash
- conformance-tests/README.md
- conformance-tests/conformance-test-remote.bash
- conformance-tests/conformance-test.bash
> Add pre-commit and fixing pre-commit errors

- README.md
Small fix to make the README not make you feel like you shouldn't change anything in the inventory.ini file that's generated and instead maybe use something else.
> Updated the README to be clearer of inventory file

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/investigation.md
> Added github issue template

- bin/common.bash
Fix from bug appearing after merging https://github.com/elastisys/compliantkubernetes-kubespray/pull/22
> Fixed unbound variable

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/investigation.md
- .mdl_style.rb
Hard to test these things when it only applies once in main
> Fixed templates not working when complying with mdl rule MD041

- bin/init.bash
- config/openstack/group_vars/all/ck8s-openstack.yaml
- config/openstack/group_vars/k8s-cluster/ck8s-k8s-cluster-openstack.yaml
- docs/citycloud-snippets.md
Added openstack/citycloud flavor and added some snippets I used to set it up with.
> Added some documentation on how to set up on citycloud + flavor

- README.md
Minor update to add all flavors in the README.
> README: update with all available flavors

- .github/pull_request_template.md
Fixes: #48
I realize we don't currently have a pipeline/tests in this repo, but I guess we should. At least we could run the pre-commit hook so that we notice if someone forgets to run it locally.
> all: Add pull request template

- README.md
- bin/apply.bash
- bin/ck8s-kubespray
- bin/common.bash
- bin/init.bash
- bin/run-playbook.bash
Removes private ssh key copying and usage.
fixes #21
> all: Remove SSH key usage

- rook/README.md
- rook/deploy-rook.sh
- rook/toolbox-deploy.yaml
Added some simple notes and deployment to help with ceph troubleshooting
**Checklist:**
> Added some simple troubleshooting info

- CHANGELOG.md
- WIP-CHANGELOG.md
> Merge QA fixes to release 2.15.0-ck8s1

- CHANGELOG.md
- WIP-CHANGELOG.md
> Merge QA fixes to main

- release/reset-changelog.sh
**What this PR does / why we need it**: Merging QA fix into release branch
**Checklist:**
> QA fix - v2.16.0-ck8s1

- release/reset-changelog.sh
**What this PR does / why we need it**: Merging the QA fixes to the main branch
**Checklist:**
> QA fixes - to main branch

- WIP-CHANGELOG.md
- rook/cluster.yaml
- rook/operator-values.yaml
- rook/toolbox-deploy.yaml
**What this PR does / why we need it**: missing resource requests for containers 
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #580
- the values for the resource requests cpu and memory are based on the containers consumption from my exo dev cluster (24h period)
- I didn't find a solution for adding resource requests to kube-proxy, kube-apiserver, kube-scheduler and kube-controller. The manifests from kubernetes do not contain this fields and cannot be added or costumized via kubeadm. We can include some manual commands/scripts to add this after the cluster is up and running, but I do not …
> apps: added resources requests to rook containers

- CHANGELOG.md
- WIP-CHANGELOG.md
**What this PR does / why we need it**: Reset changelog for new release
**Checklist:**
> Reset changelog for release v2.17.1-ck8s1 (release branch)

- release/README.md
Updates the patch release steps, the same as in the apps repo.
**Which issue this PR fixes**
**Public facing documentation PR**
**Checklist:**
> docs: Update patch release steps

- CHANGELOG.md
- config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml
- migration/v2.17.x-ck8s1-v2.18.x-ck8s1/upgrade-cluster.md
This PR adds fixes in the release branch to the main branch.
**Which issue this PR fixes** : fixes #
**Checklist:**
> Release 2.18.0 fixes

- CHANGELOG.md
- WIP-CHANGELOG.md
> Reset changelog for release v2.19.0-ck8s1

- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- WIP-CHANGELOG.md
- bin/apply.bash
- bin/common.bash
- bin/run-playbook.bash
- config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml
- migration/v2.18.0-ck8s1-v2.19.x-ck8s1/upgrade-cluster.md
- migration/v2.19.0-ck8s1-v2.19.0-ck8s2/migrate-terraform-openstack.sh
- migration/v2.19.0-ck8s1-v2.19.0-ck8s2/upgrade-cluster.md
- playbooks/cluster_admin_rbac.yml
- playbooks/kubeconfig.yml
- playbooks/templates/cluster_admin_crb.yml.j2
- playbooks/templates/kube_config_oidc.yml.j2
> Patch 2.19.0 ck8s2

- WIP-CHANGELOG.md
> Upgraded kubespray to v2.22.1

- CHANGELOG.md
- bin/common.bash
- migration/template/prepare/00-template.sh
- migration/v2.22/prepare/20-move-kubelet-image-gc-settings.sh
- migration/v2.22/upgrade-cluster.md
- scripts/migration/yq.sh
> QA fixes for upgrade cluster

- CHANGELOG.md
- bin/common.bash
- get-requirements.yaml
- migration/template/prepare/00-template.sh
- migration/v2.22/prepare/20-move-kubelet-image-gc-settings.sh
- migration/v2.22/upgrade-cluster.md
- scripts/migration/yq.sh
Merging QA fixes into main
**Checklist:**
> QA fixes for v2.22.1-ck8s1

- WIP-CHANGELOG.md
- rook/scripts/funcs.sh
- rook/scripts/test-rook.sh
> [!important]
Added a test script for `rook-ceph`.
...
- Fixes #279 
- Logs checks:
> rook: add test script

- WIP-CHANGELOG.md
> [!important]
...
- Fixes #
- Logs checks:
> Updated ingress/egress IPv6 rules

- rook/helmfile.d/charts/rook-ceph-toolbox/values.yaml
- rook/scripts/funcs.sh
- rook/scripts/pipeline/bootstrap-rook.sh
- rook/scripts/pipeline/finalise-deploy-rook.sh
- rook/scripts/pipeline/wait-for-rook.sh
- rook/scripts/pipeline/zap-disk-auto.sh
> [!important]
Added scripts and fixes to facilitate installing rook in the pipeline
- Logs checks:
> rook: fixes for pipeline after rework

- WIP-CHANGELOG.md
> [!important]
Part of kubespray release, upgraded kubespray to v2.23.0 and cherry-picked our commits that are not yet in upstream
- Fixes #
- Logs checks:
> Upgraded kubespray to v2.23.0

- rook/helmfile.d/values/networkpolicies.yaml.gotmpl
> [!important]
Added netpols for the crashcollector
Part of https://github.com/elastisys/compliantkubernetes-apps/issues/1794
- Fixes #
- Logs checks:
> rook: add crashcollector netpol

- rook/README.md
> [!important]
...
- Fixes #
- Logs checks:
> docs: fix broken link in rook README

- bin/init.bash
> [!important]
Removes unnecessary check on environment variable `$CK8S_CLOUD_PROVIDER`.
- Logs checks:
> Remove unused cloud provider env variable check

- bin/ck8s-kubespray
- bin/common.bash
- bin/generate-groups-inventory.bash
- bin/inventory-parser.bash
- bin/sync-groups-inventory.bash
- bin/upgrade-groups.bash
- config/common/group_vars/all/ck8s-kubespray-general.yaml
- docs/kubespray-upgrade-groups.md
> [!important]
Managed upgrade script
- Fixes #268 
- [] The change is transparent
- Logs checks:
> Managed upgrade script

- migration/template/upgrade-cluster.md
- migration/v2.23/upgrade-cluster.md
- migration/v2.24/upgrade-cluster.md
> [!important]
Change flags used in docs for when performing the disruptive part of a cluster upgrade, see issue for context.
- Fixes #337 
- Logs checks:
> docs: use skip_downloads flag instead of skip tags

- bin/apply.bash
- config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml
- playbooks/master_cis_benchmark_patch.yml
- playbooks/worker_cis_benchmark_patch.yml
> [!important]
- Fixes #278
- Logs checks:
> bin: Playbooks for cis benchmark patching

- .pre-commit-config.yaml
- changelog/2.24.0.md
- migration/v2.24/apply/01-fix-cp-node-taints.sh
- migration/v2.24/upgrade-cluster.md
> [!important]
...
- Fixes #
- Logs checks:
> Add changelog for release v2.24.0-ck8s1

- .pre-commit-config.yaml
- changelog/2.24.0.md
- migration/v2.24/apply/01-fix-cp-node-taints.sh
- migration/v2.24/upgrade-cluster.md
> [!important]
Fixes from QA
- Logs checks:
> Port 2.24.0 ck8s1

- CHANGELOG.md
> [!important]
Fixes [CVE-2024-21626](https://github.com/advisories/GHSA-xr7r-f8xq-vfvv)
...
- Fixes #
- Logs checks:
> Reset changelog for release v2.23.0-ck8s3

- changelog/2.24.1.md
- rook/helmfile.d/upstream/rook-ceph/templates/configmap.yaml
- rook/helmfile.d/values/cluster.yaml.gotmpl
- rook/helmfile.d/values/operator.yaml.gotmpl
- rook/migration/v1.11/prepare/diff.sh
> [!warning]
>
> [!important]
Merges staging changes to release branch
...
- Fixes #
- Logs checks:
- Bug checks:
> Staging 2.24.1 ck8s1

- .github/ISSUE_TEMPLATE/release.md
> [!warning]
>
> [!important]
Corrects the steps in the QA checklist.
- Logs checks:
- Bug checks:
> docs: Correct release template

- .gitignore
> [!warning]
>
> [!important]
Adds .DS_Store to gitignore to prevent Mac users from accidentally committing this generated file to the repo.
...
- Logs checks:
- Bug checks:
> added .DS_Store to gitignore

- changelog/2.24.1.md
> [!warning]
>
> [!important]
Staging for patch release-2.24.1-ck8s2
- Fixes #
- Logs checks:
- Bug checks:
> Staging 2.24.1 ck8s2

- .github/ISSUE_TEMPLATE/release.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
> Remove some Infra Providers from release template issue

- .github/ISSUE_TEMPLATE/release.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
> Lucian/remove some Infra Providers from the release template

- .pre-commit-config.yaml
- README.md
- changelog/2.25.0.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
> Add changelog for release v2.25.0-ck8s1

- .pre-commit-config.yaml
- README.md
- changelog/2.25.0.md
> [!warning]
>
> [!important]
Porting commits from v2.25.0-ck8s1 release.
- Fixes #
- Logs checks:
- Bug checks:
> Port 2.25.0 ck8s1

- changelog/2.24.1.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
> Staging PR for ck8s-kubespray v2.24.1-ck8s3

- changelog/2.25.0.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
> Staging PR for ck8s-kubespray v2.25.0-ck8s2

- changelog/2.24.1.md
- migration/v2.24/prepare/20-add-lb-legacy-network.sh
> [!warning]
>
> [!important]
Patch release to fix LB issue being forced to be recreated and also added possibility to change the IPSec properties
- Fixes #
- Logs checks:
- …
> Hotfix for release v2.24.1-ck8s3

- migration/v2.25/prepare/20-add-lb-legacy-network.sh
> [!warning]
>
> [!important]
Fixes bug where LB created with the legacy network field is unable to upgrade without recreating it.
Also added option to set properties for IPSec tunnels.
- Fixes #
- Logs checks:
- Network Policy …
> kubespray: Added LB legacy network fix and added ipsec properties

- changelog/2.25.0.md
- config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml
- config/openstack/group_vars/k8s_cluster/ck8s-k8s-cluster-openstack.yaml
- config/upcloud/group_vars/k8s_cluster/ck8s-k8s-cluster-upcloud.yaml
- migration/v2.25/prepare/20-add-lb-legacy-network.sh
- rook/helmfile.d/values/cluster.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
> Patch release v2.25.0-ck8s3

- migration/v2.25/README.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
> docs: Update migration guide with missing export command for variable

- changelog/2.25.0.md
> [!warning]
>
> [!important]
Port changes from release QA
- Logs checks:
- Bug checks:
> Port 2.25.0 ck8s4

- .github/CODEOWNERS
> [!warning]
>
> [!important]
Adding codeowners for this repo. @elastisys/goto-kubernetes will be codeowners for the whole repo except for files related to rook-ceph that @elastisys/goto-block-storage will be codeowners for.
- Logs checks:
- Pod Security Policy …
> all: add codeowners

- playbooks/authorized_key.yml
> [!warning]
>
> [!important]
Add support for running authorized_key playbook when using bastion hosts.
- Fixes #
- Logs checks:
- Bug checks:
> ansible: add support for bastion hosts when running authorized_key

- bin/apply.bash
- rook/README.md
- rook/helmfile.d/values/networkpolicies.yaml.gotmpl
- rook/helmfile.d/values/operator.yaml.gotmpl
- rook/helmfile.d/values/podsecuritypolicies.yaml.gotmpl
- rook/scripts/pipeline/zap-disk-auto.sh
- rook/scripts/zap-disk.sh
- rook/template/values.yaml
> [!warning]
>
> [!important]
Had some issues with Rook-Ceph NetworkPolicies, this PR addresses these as well as fixes to rook script and the apply playbook to accept flags to be able to specify another user instead of hardcoded `ubuntu` user. `ubuntu` user will still be default.
- Fixes #
- …
> Rook Ceph and apply playbook fixes

- .github/CODEOWNERS
> [!warning]
>
> [!important]
Updated the goto name to kubespray.
We now also have networking goto, but I don't think we can really put any files here under their code ownership. Let me know if you think differently @elastisys/goto-networking.
- Logs checks:
- …
> all: update codeowners with new goto area name

- rook/helmfile.d/charts/rook-ceph-dashboards/files/ceph-osd-single.json
> [!warning]
>
> [!important]
Fixes the dashboard to actually show the available space for a osd.
- Logs checks:
- Bug checks:
> grafana dashboard: fix ceph osd

- changelog/2.26.0.md
> [!warning]
>
> [!important]
Staging for patch release v2.26.0-ck8s2
- Fixes #
- Logs checks:
- Bug checks:
> Staging 2.26.0 ck8s2

- migration/v2.26/README.md
> [!warning]
>
> [!important]
Updates the migration docs for v2.26 on the UpCloud loadbalancer proxy protocol configuration.
- Logs checks:
- Bug checks:
> docs: update proxy_prot docs in v2.26 migration

- migration/ubuntu/20.04-to-24.04-openstack.md
> [!warning]
>
> [!important]
Updated Ubuntu 24.04 migration guide to include instructions for UpCloud, since the steps differ slightly.
- Logs checks:
- …
> Update Ubuntu 24.04 migration guide to include instructions for UpCloud

- migration/v2.27/README.md
- migration/v2.27/apply/00-migrate-loadbalancers.sh
- migration/v2.27/prepare/00-template.sh
- migration/v2.27/prepare/10-init.sh
> [!warning]
>
> [!important]
Add support for multiple loadbalancers in upcloud. Requires migration script. 
...
- Fixes #
- Logs checks:
- Bug checks:
> Support multiple loadbalancers for upcloud environments

- changelog/2.27.0.md
- config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml
- migration/v2.27/README.md
- migration/v2.27/apply/00-migrate-upcloud-loadbalancer-state.sh
- migration/v2.27/prepare/20-keep-calico-version.sh
- migration/v2.27/prepare/30-reserved-resources.sh
> [!warning]
>
> [!important]
Port changes from v2.27.0-ck8s1 release
- Logs checks:
- Bug checks:
> Port 2.27.0 ck8s1

- changelog/2.26.0.md
> [!warning]
>
> [!important]
Port changes from v2.26.0-ck8s4 (just changelog)
- Logs checks:
- Bug checks:
> Port v2.26.0-ck8s4

- changelog/2.27.0.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
> Staging 2.27.0 ck8s2

- changelog/2.27.0.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
> Add changelog for release v2.27.0-ck8s2

- changelog/2.26.0.md
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
> Add changelog for release v2.26.0-ck8s5

- changelog/2.28.0.md
- migration/v2.28/prepare/40-disable-openstack-lb.sh
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
> Port 2.28.0-ck8s1 to main
