rook/README.md, rook/cluster.yaml, rook/deploy-rook.sh, rook/operator-values.yaml, rook/storageclass.yaml
This adds initial support for installing Rook on a fresh Kubernetes installation.
Only RBD volumes has been tested. The CephFS driver has been disabled to save resources.
So far monitoring is disabled by default, since it is not assumed that the Prometheus Operator CRDs are available.
Monitoring can be enabled at a later stage by setting `spec.monitoring.enabled=true` in `cluster.yaml` and reapplying.
The resource requests are an initial guess from running a Compliant Kubernetes service cluster with Rook, and does therefore not necessarily make sense.
For testing purposes, it could make sense to
* reduce the `mon` replica count to 1
* reduce the storageclass replication to 1
=> Initial rook support

README.md, bin/apply.bash, bin/ck8s-kubespray, bin/run-playbook.bash
This PR adds the option to pass arguments to ansible through the wrapper.
fixes #6 
Examples: 
```
./bin/ck8s-kubespray apply wc --version
...
[ck8s] Running kubespray
ansible-playbook 2.9.6
...
```
```
./bin/ck8s-kubespray run-playbook wc facts.yml --help
...
[ck8s] Running kubespray
usage: ansible-playbook [-h] [--version] [-v] [-k]
[--private-key PRIVATE_KEY_FILE] [-u REMOTE_USER]
[-c CONNECTION] [-T TIMEOUT]
[--ssh-common-args SSH_COMMON_ARGS]
[--sftp-extra-args SFTP_EXTRA_ARGS]
[--scp-extra-args SCP_EXTRA_ARGS]
...
```
=> bin: ansible options can be passed via wrapper

config/group_vars/all/all.yml, config/group_vars/all/azure.yml, config/group_vars/all/containerd.yml, config/group_vars/all/docker.yml, config/group_vars/all/openstack.yml, config/group_vars/k8s-cluster/addons.yml, config/group_vars/k8s-cluster/k8s-cluster.yml, config/group_vars/k8s-cluster/k8s-net-calico.yml, config/group_vars/k8s-cluster/k8s-net-kube-router.yml, config/group_vars/k8s-cluster/k8s-net-macvlan.yml
To support Ubuntu 20.04 *(and just to update to the latest version as soon as possible)* we want to update kubespray to the latest version. It works with the same inventory as v2.13
=> Updated to kubespray v2.14.2

config/gcp/group_vars/all/ck8s-gcp.yaml, config/gcp/group_vars/k8s-cluster/ck8s-k8s-cluster-gcp.yaml
Added a few more variables to group vars, which are necessary to get the GCP persistent disk driver to work (see [this document](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/gcp-pd-csi.md) and [this file](https://github.com/kubernetes-sigs/kubespray/blob/release-2.14/inventory/sample/group_vars/all/gcp.yml)).
fixes #45
=> gcp: add a few necessary variables

bin/apply.bash
Fixes #37
After kubespray has completed creating a cluster, admin.conf should be copied to .state/kube_config_[cluster].yaml However, currently this gives an error due to the .state directory not existing.
This PR creates that dir if it doesnt exist.
=> bug: kubeconfig now copied to .state dir after install

bin/init.bash
=> bin: Decrement arg count for init

docs/migrate-from-cluster.md
Added migration guide
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*:
fixes elastisys/ck8s-ops#47
**Checklist:**
=> Added migration guide from ck8s-cluster

README.md, bin/apply-ssh.bash, bin/ck8s-kubespray, config/common/group_vars/all/ck8s-ssh-keys.yaml, playbooks/authorized_key.yml
**What this PR does / why we need it**: Adds a command to the `ck8s-kubespray` wrapper that enables changing authorized SSH keys for a cluster.
**Which issue this PR fixes**: fixes an issue in an internal repository
**Checklist:**
=> bin: add apply-ssh command to change SSH keys

config/openstack/group_vars/k8s-cluster/ck8s-k8s-cluster-openstack.yaml
To get citycloud work with the dynamic inventory
**Checklist:**
=> Added kubeadm etcd for openstack

bin/common.bash
Since `~` isn't expanded by `readlink` when it's in a variable I would suggest this small fix to make us able to use `~` to reference `${HOME}`
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: 
N/A
**Checklist:**
=> Replace ~ with $HOME so absolute path expansion works

bin/apply.bash, bin/common.bash, bin/run-playbook.bash, docs/citycloud-snippets.md
This fixes a couple of small issues.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #31, fixes #61
I'm not sure if it is a good idea to set `TERRAFORM_STATE_ROOT` in `common.bash` or if it would be better to set it in the `run-playbook.bash` and `apply.bash` scripts instead. What do you think?
**Checklist:**
=> Small fixes: dynamic inventory path; don't force become

bin/common.bash
readlink -f does not work for all paths that do not exists.
This changes it to use -m instead.
```
-m, --canonicalize-missing    canonicalize by following every symlink in
every component of the given name recursively,
without requirements on components existence
```
**Checklist:**
=> bin: Fix CK8S_CONFIG_PATH creation

bin/apply.bash, bin/run-playbook.bash
Installing the Kubespray requirements in a virtual environment is great but in certain circumstances you might want to rely on everything being installed in your current environment / system. A good example would be a pre-built Docker image where the current Kubespray version we target is already installed.
I'm not set on the `CK8S_KUBESPRAY_NO_VENV` env name. Feel free to suggest a different, more fitting one.
**Checklist:**
=> Allow skipping venv and requirements installation 

README.md, bin/init.bash, config/vsphere/group_vars/k8s-cluster/ck8s-k8s-cluster-vsphere.yaml
To support vSphere setups, this makes your life it easier.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: 
**Checklist:**
=> Added config for vSphere

config/common/group_vars/k8s-cluster/ck8s-k8s-cluster.yaml
To be able to use groups for the kube-apiserver we need to set  this variable. Might as well have it as default.
**Checklist:**
=> Added oidc groups claim in the common config

.pre-commit-config.yaml, bin/apply-ssh.bash, bin/apply.bash, bin/ck8s-kubespray, bin/init.bash, bin/run-playbook.bash
Using `shellcheck --external-sources` makes shellcheck pick up variables defined in sourced scripts. This allows us to not exclude certain rules. However, they need to be disabled for venv since it doesn't always exist.
=> pre-commit: Use shellcheck --external-sources

.editorconfig, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .pre-commit-config.yaml, CHANGELOG.md, WIP-CHANGELOG.md, release/README.md, release/reset-changelog.sh
This adds release docs/pipeline, pre-commit pipeline, editor config, and some minor fixes.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #90
Please go through the release doc thoroughly since I had to adapt it to the version numbers we use in this repo (e.g. v2.16.0-ck8s1). 
**Checklist:**
=> Release docs, precommit pipeline, and general fixes

release/reset-changelog.sh
**What this PR does / why we need it**: Small typo in the reset-changelog script
**Checklist:**
=> release: fix typo in release script

WIP-CHANGELOG.md, config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml
**What this PR does / why we need it**: This will enable Calico Felix metrics reporting
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #42 
**Checklist:**
=> config: enabled calico metrics reporting

migration/v2.15.0-ck8s1-v2.16.0-ck8s1/upgrade-cluster.md
**What this PR does / why we need it**: Updates the 2.15 -> 2.16 migration doc with some necessary steps. Since this change won't be on the release tag, the person doing the upgrade should be referred to the document on the main branch instead.
**Which issue this PR fixes**: none
**Checklist:**
=> docs: update 2.15 -> 2.16 migration doc

README.md, WIP-CHANGELOG.md, bin/ck8s-kubespray, bin/reboot-nodes.bash, playbooks/reboot_nodes.yml
**What this PR does / why we need it**: This adds a command/playbook to reboot all nodes in a cluster if necessary.
I'm not sure I like how all of the tasks are written, so feel free to suggest alternate implementations.
Based on https://github.com/savoirfairelinux/ansible-reboot-if-needed
**Checklist:**
=> bin: add command to reboot nodes

WIP-CHANGELOG.md, config/openstack/group_vars/k8s_cluster/ck8s-k8s-cluster-openstack.yaml
**What this PR does / why we need it**: Updates the openstack config to use the external cloud controller.
**Which issue this PR fixes**: fixes #91
**Special notes for reviewer**: Someone who's familiar with the config, tell me if some more config should be added to the defaults.
**Checklist:**
=> config: update openstack config to use external cloud controller

CHANGELOG.md, rook/README.md, rook/remove-rook.sh, rook/zap-disk, rook/zap-disk.sh
This adds scripts and instructions how to remove Rook. Needed for [#299](https://github.com/elastisys/ck8s-ops/issues/299)
**Which issue this PR fixes** : 
**Checklist:**
=> apps: Scripts and instructions how to remove rook

WIP-CHANGELOG.md, config/openstack/group_vars/k8s_cluster/ck8s-k8s-cluster-openstack.yaml
This sets Cinder CSI as the default storage provider on Openstack while enabling volume expansion on new clusters.
**Which issue this PR fixes**: 
fixes #110 
https://github.com/elastisys/compliantkubernetes/pull/177
**Checklist:**
=> config: Update Openstack config to use Cinder by default

README.md, bin/reboot-nodes.bash, playbooks/reboot_nodes.yml
Added a note that there is a known issue for the reboot script. I could not recreate the bug, i tried multiple ways to make the step fail but the error was never the same. 
The error occurs if the `kubelet_heartbeat` is not registered in the playbook, which is unclear why it happens. 
I also increased the number of retries, as it may be because of to few retries.
**Which issue this PR fixes**:
fixes #112 
**Checklist:**
=> docs: Added known issue for rebooting node script

release/README.md
This updates the release document to include updating the user-facing release notes.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes elastisys/compliantkubernetes#148
**Checklist:**
=> docs: Update release document to include user-facing release notes

rook/operator-values.yaml
**What this PR does / why we need it**:  I have added in commented lines the "provisionerTolerations" and "pluginTolerations". These are needed for Exoscale and other cloud providers where we use rook-ceph. It is needed to be able to schedule the csi-rbdplugin pods on nodes that are tainted and be able to mount volumes on those tainted nodes.
Without this, the tainted nodes will not have the csi-rbdplugin pods running on them, and without that the nodes will fail to mount volumes with the following error:
_FailedMount  9m25s (x461 over 15h)  kubelet  MountVolume.MountDevice failed for volume "pvc-9e7ec0da-d52d-46b8-bd74-e5262286cb0d" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name rook-ceph.rbd.csi.ceph.com not found in the list of registered CSI …
=> apps:rook add provisioner and plugin tolerations for tainted nodes

README.md, WIP-CHANGELOG.md, playbooks/reboot_nodes.yml
**What this PR does / why we need it**: The reboot script now drains each node before rebooting them.
**Checklist:**
=> bin: add drain to reboot script

WIP-CHANGELOG.md, migration/v2.17.0-ck8s1-v2.17.1-ck8s1/upgrade-cluster.md
**What this PR does / why we need it**: Upgrade to kubespray v2.17.1
**Special notes for reviewer**: I added migration steps for 2.17.0 -> 2.17.1, but I'm gonna try if 2.16.0 -> 2.17.1 is possible directly. If so, I'll change the migration docs during the QA process.
**Checklist:**
=> all: update kubespray to v2.17.1

rook/deploy-rook.sh
Adds `owner=operator` label to rook-ceph namespace to exclude it from OPA policies.
**Which issue this PR fixes**: 
fixes elastisys/compliantkubernetes-apps#620
**Checklist:**
=> apps: Add owned by operator label to rook namespace

rook/storageclass.yaml, rook/toolbox-deploy.yaml
To reclaim data that is deleted in a pvc we should have this mount option as default. See [this](https://github.com/rook/rook/issues/3832)
**Checklist:**
=> rook: Set discard as default mount option

migration/v2.16.0-ck8s1-v2.17.x-ck8s1/upgrade-cluster.md
**What this PR does / why we need it**: to update the migration docs on how to enable calico felix metrics
**Checklist:**
=> docs: updated the migration docs

bin/apply.bash, bin/common.bash, bin/run-playbook.bash
**What this PR does / why we need it**: Adds some checks for openstack credentials and a prompt for the user to hopefully catch when a user would accidentally use the wrong credentials.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #146 
Some examples:
No credentials set:
`OS_USERNAME` and `OS_PASSWORD` are set:
`OS_APPLICATION_CREDENTIAL_SECRET` is missing:
Both openstack user and openstack application credentials are set:
**Checklist:**
=> bin: add prompt and checks for openstack credentials

WIP-CHANGELOG.md, bin/ck8s-kubespray, bin/prune-docker.bash, config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, docs/adding-kubelet-args-to-existing-environment.md, migration/v2.18.0-ck8s1-v2.19.x-ck8s1/upgrade-cluster.md, playbooks/ansible.cfg, playbooks/prune_docker.yml
When running ceph some nodes can become in a warning state as storage is low. I have seen that docker can have a lot of unused images, up to 20GB. So a easy step is to clear docker and this ansible will clear it up.
Also added ansible config file so that host key is not checked.
**Checklist:**
=> ansible: docker prune

rook/deploy-rook.sh, rook/toolbox-deploy.yaml
The rook-ceph-toolsbox image change and CrashLoops if created with the wrong Deployment. Pulling the latest version.
Also, the deploy script is not idempotent and may fail with:
```
error: 'owner' already has a value (operator), and --overwrite is false
```
N/A
N/A
**Checklist:**
=> Rook fixes

docs/citycloud-proxy-protocol-workaround.md
To get source IP preservation in citycloud clusters.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: 
**Checklist:**
=> docs: Added instructions to enable proxy protocol on citycloud

.pre-commit-config.yaml
Added pre-commit hook that stops commits to the main branch.
**Which issue this PR fixes** : fixes (1478 in ck8s-ops)
**Checklist:**
=> tests: added pre-commit hook that stops commits to main

WIP-CHANGELOG.md, config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, migration/v2.17.x-ck8s1-v2.18.x-ck8s1/upgrade-cluster.md, migration/v2.18.0-ck8s1-v2.18.1-ck8s1/upgrade-cluster.md
We want to upgrade to etcd 3.5.3 as soon as possible because of a data inconsistency issue.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #171
**Checklist:**
=> config: Updated default config to use etcd 3.5.3

.gitmodules, WIP-CHANGELOG.md
Switch to elastisys fork of kubespray and update kubespray to v2.18.1 together with psp fix.
**Checklist:**
=> kubespray: switch to our fork for psp fix

migration/v2.17.x-ck8s1-v2.18.x-ck8s1/upgrade-cluster.md, migration/v2.18.0-ck8s1-v2.18.1-ck8s1/upgrade-cluster.md
To not confuse git command in kubespray folder.
=> docs: Updated migration docs to sync remote

WIP-CHANGELOG.md, bin/ck8s-kubespray, bin/remove-node.bash
**Which issue this PR fixes**:
fixes #175 
**Checklist:**
=> bin: add remove-node command

migration/v2.17.x-ck8s1-v2.18.x-ck8s1/upgrade-cluster.md
**What this PR does / why we need it**: Maintenance-docs updated: Updating-docker-pruning-steps
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #186 
**Checklist:**
=> Maintenance-docs: updating-docker-pruning-steps

README.md
The remove-node command was added to ck8s-kubespray, but not described in the README.
This PR fixes that.
**Checklist:**
=> docs: added remove-node command to readme

.pre-commit-config.yaml, migration/v2.17.x-ck8s1-v2.18.x-ck8s1/migrate-to-containerd.yml, migration/v2.17.x-ck8s1-v2.18.x-ck8s1/upgrade-cluster.md, migration/v2.18.0-ck8s1-v2.19.x-ck8s1/migrate-to-containerd.yml, migration/v2.18.0-ck8s1-v2.19.x-ck8s1/upgrade-cluster.md
adds containerd migration script
**Checklist:**
=> added migration script to containerd

.gitmodules, WIP-CHANGELOG.md, migration/v2.18.0-ck8s1-v2.19.x-ck8s1/upgrade-cluster.md
Upgrade to new kubespray upgrade
**Checklist:**
=> kubespray: upgrade to v2.19.0

.gitmodules, CHANGELOG.md, WIP-CHANGELOG.md, migration/v2.18.0-ck8s1-v2.19.x-ck8s1/upgrade-cluster.md
Reset changelog 
**Checklist:**
=> Reset changelog for release v2.19.0-ck8s1

.pre-commit-config.yaml, WIP-CHANGELOG.md, bin/apply.bash, bin/common.bash, bin/run-playbook.bash
If you miss to do a submodule update after checking out a version of ck8s-kubespray then you might install the wrong version of kubernetes or get other errors. This is now fixed by adding a dialog for if the kubespray git submodule differs from the expected status.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #163
**Checklist:**
=> kubespray diff check

migration/v2.19.0-ck8s1-v2.19.0-ck8s2/migrate-terraform-openstack.sh, migration/v2.19.0-ck8s1-v2.19.0-ck8s2/upgrade-cluster.md
**What this PR does / why we need it**: Added migration script for the terraform state for v2.18 -> v2.19 for openstack environments to prevent terraform from trying to recreate nodes.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #176
The issue states that the script should make it so that terraform doesn't want to change anything, but I think because of how significantly the terraform module has changed this is not really viable. The script will make it so that terraform doesn't try to destroy anything important, but it will make some changes to the state.
I have tried this on safespring …
=> bin: add openstack terraform migration script for 2.18 -> 2.19

migration/v2.19.0-ck8s1-v2.19.0-ck8s2/upgrade-cluster.md
**What this PR does / why we need it**: Updated the migration guide steps for the openstack terraform state with some config that is necessary for Safespring environments, and made the rest of the steps a bit more clear.
**Checklist:**
=> docs: update migration guide for v2.19.0-ck8s2

.gitmodules, CHANGELOG.md, config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, config/openstack/group_vars/k8s_cluster/ck8s-k8s-cluster-openstack.yaml, migration/v2.18.0-ck8s1-v2.19.x-ck8s1/clear-old-ansible-versions.sh, migration/v2.18.0-ck8s1-v2.19.x-ck8s1/upgrade-cluster.md
fixes from 2.19.0 release branch
**Checklist:**
=> Release 2.19.0 fixes

.pre-commit-config.yaml, CHANGELOG.md, WIP-CHANGELOG.md, migration/v2.18.0-ck8s1-v2.19.x-ck8s1/upgrade-cluster.md, migration/v2.19.0-ck8s1-v2.19.0-ck8s2/upgrade-cluster.md
Added commit for reset of WIP
Fix small issues in migration doc for v2.18 -> v2.19
**Checklist:**
=> Doc: fix migration doc

README.md
The current wording -- in particular the word "alpha" -- makes the project sound immature. This is in contrast to the fact that the project successfully serves a double-digit production environments with high up-time. Hence, let's fix the wording to give the project the praise it deserves. :smile:
**Checklist:**
=> Clarify API stability

WIP-CHANGELOG.md, bin/common.bash
Changed to use yq version 4
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #202
**Checklist:**
=> bin: Updated to yq4

WIP-CHANGELOG.md, config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, migration/v2.19.0-ck8s2-v2.20.x-ck8s1/upgrade-cluster.md
Added fixes for cis kube-bench tests that fail for the master nodes.
I just found that kubespray have this [document](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/hardening.md) about hardening. Could be worth going through it. 
**Checklist:**
=> config: fix for cis kube-bench test fail

release/README.md
Updated link to public release docs
**Checklist:**
=> docs: updated release docs

release/README.md
=> docs: fix links to public docs

config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, migration/v2.19.x-ck8sx-v2.20.x-ck8s1/upgrade-cluster.md, playbooks/templates/kube_config_oidc.yml.j2
Fix cluster.local in kubeconfigs
**Checklist:**
=> ck8s:Fix cluster.local in kubeconfigs

WIP-CHANGELOG.md, migration/v2.19.x-ck8sx-v2.20.x-ck8s1/upgrade-cluster.md
Bump upcloud csi driver
**Checklist:**
=> upcloud csi driver: bump version to v0.3.3

WIP-CHANGELOG.md, config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, migration/v2.19.x-ck8sx-v2.20.x-ck8s1/upgrade-cluster.md
Changed a Kubespray variable which is required for upgrading clusters on cloud providers that don't have external IPs on their control plane nodes. i.e. Safespring
**Checklist:**
=> config: changed variable for upgrading cp nodes without external ip

WIP-CHANGELOG.md, migration/v2.20.0-ck8s2-v2.20.0-ck8s3/upgrade-cluster.md
Updated kubespray to use our fork with 2.20 + terraform changes for node override variables and additional server groups
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #174 
**Checklist:**
=> kubespray: Updated to 2.20.0 with new terraform changes

WIP-CHANGELOG.md, rook/cluster.yaml
**What this PR does / why we need it**: Enabled ceph dashboard as it gives better detailed visibility and troubleshooting ceph cluster . It does't uses the extra resources/pods and run on the same pod `mgr` with different port `7000` with separate service `rook-ceph-mgr-dashboard`
**Checklist:**
=> rook-ceph: Enabled ceph dashboard

WIP-CHANGELOG.md, rook/deploy-rook.sh, rook/migration/rook-1.5.x-rook-1.10.5/cluster-16.2.10.yaml, rook/migration/rook-1.5.x-rook-1.10.5/cluster-17.2.5.yaml, rook/migration/rook-1.5.x-rook-1.10.5/upgrade.md, rook/operator-values.yaml, rook/toolbox-deploy.yaml
Upgrades the rook-ceph operator and ceph.
**Which issue this PR fixes**:
Fixes #131 
- I will take a look at the prometheus alerts in apps in a while.
- I did not really find that we needed to modify anything in the operator values or the cluster manifest.
- I decided that it was safest to upgrade the operator one step at a time as it is then easier to debug and recover if a problem were to occur.
**Checklist:**
=> Upgrade ceph

migration/v2.18.0-ck8s1-v2.19.x-ck8s1/migrate-to-containerd.yml
Remove the rest of docker files after migrating to containerd
**Checklist:**
=> Remove rest of docker files

migration/v2.18.0-ck8s1-v2.19.x-ck8s1/migrate-to-containerd.yml
Remove `/var/lib/docker` after reboot
I haven't tested it, but I think this should work?
**Checklist:**
=> migration: Update containerd migration

migration/v2.19.x-ck8sx-v2.20.x-ck8sx/upgrade-cluster.md
updated migration doc to include containerd version change
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #246
**Checklist:**
=> updated migration doc to include containerd version change

README.md, WIP-CHANGELOG.md, get-requirements.yaml
We had a discussion in the office and thought it make more sense to go with terraform `1.2.9` for now, that way we don't have to make a new patch release for ck8s-kubespray to fix the experimental feature issue we ran into with terraform `1.3+`. This way we are also closer to what the upstream kubespray repo is using.
Tested running Kubespray on `v2.20.0-ck8s3` with this terraform version (`1.2.9`) and I had no issues.
**Which issue this PR fixes** : fixes #248 
**Checklist:**
=> all: added get-requirements file to standardize terraform

WIP-CHANGELOG.md, config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, migration/v2.20.0-ck8sx-v2.21.0-ck8sx/upgrade-cluster.md
Add ntp.se as ntp server
**Which issue this PR fixes**: fixes #250 
After applying one can check ntp on the nodes:
```bash
ntpq -pn
remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
gbg1.ntp.netnod .POOL.          16 p    -   64    0    0.000    0.000   0.000
gbg2.ntp.netnod .POOL.          16 p    -   64    0    0.000    0.000   0.000
lul1.ntp.netnod .POOL.          16 p    -   64    0    0.000    0.000   0.000
lul2.ntp.netnod .POOL.          16 p    -   64    0    0.000    0.000   0.000
mmo1.ntp.netnod .POOL.          16 p    -   64    0    0.000    0.000   0.000 …
```
=> config: add ntp.se as ntp server as migration step

bin/apply.bash, bin/remove-node.bash, bin/run-playbook.bash
**What this PR does / why we need it**: Fixed a few typos in messages that are shown when running `bin/ck8s-kubespray` commands.
**Checklist:**
=> bin: fix typos in status messages

migration/create-migration-document.sh, release/README.md
=> docs: added prompt to migration doc creation script

WIP-CHANGELOG.md, bin/run-playbook.bash
Tested adding 10 worker nodes to a cluster and ran the upgrade playbook (with --tags=network) with and without this change. It did these plays ([this](https://github.com/kubernetes-sigs/kubespray/blob/df1bdb22928312cd5703a4be5017d9d6d50dc875/upgrade-cluster.yml#L109) & [this](https://github.com/kubernetes-sigs/kubespray/blob/df1bdb22928312cd5703a4be5017d9d6d50dc875/upgrade-cluster.yml#L122)) one worker node at a time when setting `-e serial=1` and two at a time without it.
I also tried running another playbook `scale.yml` via the `run-playbook` binary and it worked normally when setting `-e serial=1` as it doesn't use this variable.
**Which issue this PR fixes** : fixes #208 
**Checklist:**
- Is this changeset backwards compatible for existing …
=> bin: defaulted to serial execution in upgrade playbook

WIP-CHANGELOG.md, playbooks/reboot_nodes.yml
Changed reboot script to use the hostnames specified in the inventory file instead of the actual hostnames of the machines. This allows for the `override_system_hostname: false` setting to be used.
**Which issue this PR fixes**: fixes #261
**Checklist:**
=> bin: changed to inventory hostnames in reboot script

CHANGELOG.md
For metallb we need to have support to override network ID on individual nodes which was missed when we did the last patch. So this would fix that. But this is part of the kubespray 2.21 release so we don't need to fix it on main
**Checklist:**
=> Updated kubespray to support network id

config/gcp/group_vars/all/ck8s-gcp.yaml
In Kubespray the 'cloud_provider' var must be set either to 'gce' for Google Cloud
When deploying Compliant Kubernetes in Google Cloud, the cloud_provider variable needs to be defined as gce. Not gcp
I haven't created an issue. Should I?
**Checklist:**
=> config: Fixed cloud provider

WIP-CHANGELOG.md, migration/v2.20.0-ck8sx-v2.21.0-ck8s1/upgrade-cluster.md, rook/deploy-rook.sh, rook/operator-values.yaml
Add PSA labels and disable Kubernetes PSPs for rook-ceph
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: Part of fix for [#1451](https://github.com/elastisys/compliantkubernetes-apps/issues/1451)
**Checklist:**
=> rook-ceph: Add PSA labels and disable PSP

migration/v2.20.0-ck8sx-v2.21.0-ck8s1/bypass-k8s-psp.sh, migration/v2.20.0-ck8sx-v2.21.0-ck8s1/upgrade-cluster.md
An [issue](https://github.com/elastisys/compliantkubernetes-kubespray/issues/274) was found with the 2.20->2.21 migration for rook-ceph that I missed in the original PR for the PSP replacement.  
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #274 
I was able to recreate the issue and test the proposed solution which worked perfectly. Another possible option would be to run kubespray to only disable PSP->Upgrade rook-ceph operator to remove PSP/RBAC->Continue with the actual cluster upgrade. This would take more work and time however in comparison to this solution. Could probably do some PSP bypass …
=> rook-ceph: Update migration docs

WIP-CHANGELOG.md, bin/ck8s-kubespray, bin/common.bash
Adds the same dependency version check as in apps.
Only includes terraforms versioning.
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: continuation on https://github.com/elastisys/compliantkubernetes-apps/issues/1478
**Checklist:**
=> bin: Add dependency check

bin/common.bash
**What this PR does / why we need it**: If `bin/ck8s-kubespray <apply|run-playbook>` was executed from somewhere other than the `compliantkubernetes-kubespray` repository, the git version check would fail. This fixes that problem.
**Checklist:**
=> bin: fix version check to work from anywhere

CHANGELOG.md, migration/v2.21/prepare/15-set-unprivileged.sh
**What this PR does / why we need it**: fix typo in the migration scripts
=> fix: migration script typo

rook/scripts/zap-disk, rook/scripts/zap-disk.sh, rook/template/values.yaml
Found two issues when trying it out.
**Checklist:**
=> rook: zap and values fixes

config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, docs/local-volume-provisioner.md
**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*: fixes #238 
**Checklist:**
=> added config to enable local volume provisioner

bin/ck8s-kubespray, bin/upgrade.bash, migration/template/prepare/00-template.sh, migration/template/prepare/10-init.sh, migration/template/upgrade-cluster.md, scripts/migration/lib.sh
> [!important]
This PR changes the number of arguments required to run the `upgrade` command, as with this PR you need to specify the specific cluster, `sc`, `wc`, or `both` to apply to both clusters as the command did previously. The `ck8s-kubespray` usage has been updated to clarify this:
```bash
➜ ./bin/ck8s-kubespray         
COMMANDS:
...
upgrade                                     prepares config for upgrade
args: <wc|sc|both> <version> prepare
```
This PR allows for running the `upgrade prepare` …
=> bin: allow per cluster upgrade prepare

README.md, bin/apply-ssh.bash, bin/apply.bash, bin/ck8s-kubespray, bin/common.bash, bin/init.bash, bin/prune-nerdctl.bash, bin/reboot-nodes.bash, bin/remove-node.bash, bin/run-playbook.bash, docs/citycloud-snippets.md
> [!important]
`ck8s-kubespray` commands no longer support using other prefixes besides `sc` or `wc`.
The compliantkubernetes-apps repo forces cluster config names to be `wc` and `sc` while the compliantkubernetes-kubespray repo has previously supported custom prefixes for cluster config. This PR helps standardize the repositories by enforcing the `wc` and `sc` cluster naming convention.
- Fixes #314 
- Logs checks:
- …
=> Force sc wc cluster names

playbooks/authorized_key.yml
> [!important]
Automate authorized key playbook when there is a conflicting public key.
...
- Fixes #
The authorized key playbook used by apply-ssh automatically removes conflicting keys for a hosts IP. This to remove the annoying prompt needing to remove or accept a key.  
- Logs checks:
=> playbook: remove/add ip to known_host

config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml
> [!important]
Add tolerations for coredns so it doesn't get stuck in "pending" on cluster creation.
- Fixes #350 
- Logs checks:
=> config: add extra tolerations for coredns

playbooks/authorized_key.yml, playbooks/reboot_nodes.yml
> [!important]
When running `apply-ssh` on `v2.24.0-ck8s1` on openstack environments it would fail with
```
TASK [For each host, scan for its ssh public key] ****************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: …
```
=> playbook: switch to ansible_host in authorized_key.yml

rook/helmfile.d/values/cluster.yaml.gotmpl, rook/template/values.yaml
With Linux kernel 5.4 (which shipped, for example, with Ubuntu 20.04 LTS) several new Ceph RBD image features was implemented. The rook-ceph defaults, however, does not reflect this fact, and the existing default ("layering") is recommended only for kernels prior to 5.4. Adding the ability to set "imageFeatures" defaults when deploying rook-ceph aims to mitigate this.
From rook-ceph's documentation:
"Rook's default RBD configuration specifies only the layering feature, for broad compatibility with older kernels. If your Kubernetes nodes run a 5.4 or later kernel, additional feature flags can be enabled in the storage class. The fast-diff and object-map features …
=> rook: Add ability to set RBD image features

config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, migration/v2.25/README.md, migration/v2.25/prepare/30-ntp-filter-interfaces.sh
> [!warning]
>
> [!important]
config: added a migration step to filter interfaces
- Fixes #
- Logs checks:
- Bug checks:
=> config: added a migration step to filter interfaces

changelog/2.24.1.md
> [!warning]
>
> [!important]
Patch release-2.24.1-ck8s2 to update Kubespray submodule with private cloud lb and anti affinity changes for Upcloud
- Fixes #
- Logs checks:
- …
=> Port 2.24.1 ck8s2

changelog/2.25.0.md, migration/v2.25/README.md, migration/v2.25/prepare/20-add-lb-legacy-network.sh
> [!warning]
>
> [!important]
Patch release v2.25.0-ck8s4.
Some notes regarding the changelog:
- We had several commits in the `kubespray` submodule that are represented by just one commit in the `compliantkubernetes-kubespray` repo, so I added the individual commits in the submodule into the …
=> Staging 2.25.0 ck8s4

migration/v2.25/README.md
> [!warning]
>
> [!important]
Updated the migration docs since the calico config is not necessary for the new patch release of `v2.25.0`.
- Logs checks:
- Bug checks:
=> docs: skip calico config for v2.25.0-ck8s4

rook/helmfile.d/charts/rook-ceph-rules/files/rules.yaml
> [!warning]
>
> [!important]
...
Fixes many-to-many evaluation errors in Thanos for some rook-ceph alert rules.
- Fixes #
`Error: many-to-many matching not allowed: matching labels must be unique on one side\"}\n" query="(rate(ceph_osd_up[5m]) * on (ceph_daemon) group_left (hostname) …
=> rook-ceph: fix alerts

docs/managing-kubespray-fork.md, release/README.md
> [!warning]
>
> [!important]
Updated process of handling the kubespray fork.
Create one release branch `release-X.Y.Z-ck8s` in our fork per upstream release `X.Y.Z`. We then tag the latest commit of that release branch with `vX.Y.Z-ck8s<patch-number>`.
- Logs …
=> docs: updated fork process

rook/helmfile.d/charts/rook-ceph-rules/files/rules.yaml
> [!warning]
>
> [!important]
...
- Fixes [#335](https://github.com/elastisys/ck8s-issue-tracker/issues/335)
- Logs checks:
- Bug checks:
=> rook-ceph: remove ceph node packet drops alert

changelog/2.26.0.md
> [!warning]
>
> [!important]
Ported changelog commit from `v2.26.0-ck8s2` release branch.
- Fixes #
- Logs checks:
- Bug checks:
=> Port v2.26.0-ck8s2

migration/ubuntu/20.04-to-24.04-openstack.md, migration/ubuntu/gen-inventory.sh
> [!warning]
>
> [!important]
Migration docs for how to migrate to ubuntu 24.04
- Fixes elastisys/ck8s-issue-tracker#348
- Logs checks:
- Bug checks:
=> docs: Added guide to migrate to Ubuntu 24.04

docs/managing-kubespray-fork.md
> [!warning]
>
> [!important]
Updated our Kubespray fork to v2.27.0.
- Fixes #412 
Followed the [fork process](https://github.com/elastisys/compliantkubernetes-kubespray/blob/main/docs/managing-kubespray-fork.md). Our master branch is now based on v2.27.0, and the submodule is checked out on the …
=> Upgrade kubespray fork to v2.27.0

README.md, bin/init.bash, config/aws/group_vars/k8s_cluster/ck8s-k8s-cluster-aws.yaml, config/common/group_vars/all/ck8s-kubespray-general.yaml, config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, config/openstack/group_vars/k8s_cluster/ck8s-k8s-cluster-openstack.yaml, config/upcloud/group_vars/k8s_cluster/ck8s-k8s-cluster-upcloud.yaml, config/vsphere/group_vars/k8s_cluster/ck8s-k8s-cluster-vsphere.yaml
> [!warning]
>
> [!important]
Added support for initializing upcloud config
Updated default config
Added support for initializing upcloud config
- Part of https://github.com/elastisys/ck8s-issue-tracker/issues/352
- Logs checks:
- …
=> Revise default config

rook/helmfile.d/charts/rook-ceph-dashboards/files/ceph-cluster.json, rook/helmfile.d/values/podsecuritypolicies.yaml.gotmpl
> [!warning]
>
> [!important]
...
- Fixes #
- Logs checks:
- Bug checks:
=> rook-ceph: add exporter psp and fix dashboard

rook/scripts/autoconfig.sh
> [!warning]
>
> [!important]
After moving from the rook netpols in apps we saw a lot of errors with rook, and we traced it down to csi-rbdplugin and krbd using host network, which would come from these VXLAN source addresses, and would then get dropped by the network policy
This change adds the …
=> rook: add calico vxlan ips to peers, and support ipv6

rook/helmfile.d/values/networkpolicies.yaml.gotmpl, rook/helmfile.d/values/operator.yaml.gotmpl, rook/helmfile.d/values/podsecuritypolicies.yaml.gotmpl, rook/template/values.yaml
> [!warning]
>
> [!important]
These changes add the ability to enable the cephfs csi driver, which provides RWX volumes. CephFS is a posix compliant file system that can be mounted by multiple clients simultaneously, and is useful in some user workloads where shared storage is needed. Enabling …
=> rook: add option to enable cephfs csi

config/common/group_vars/all/ck8s-containerd.yaml
> [!warning]
>
> [!important]
This PR adds a template for both clusters for using private registry mirror, the credential will be read by ansible and pass to the containerd host template in https://github.com/elastisys/kubespray/pull/25 …
=> Add containerd config template for private registry

changelog/2.26.0.md
> [!warning]
>
Update default containerd version to v1.7.27 to mitigate [CVE-2024-40635](https://nvd.nist.gov/vuln/detail/CVE-2024-40635). 
> [!important]
...
- Fixes #
- Logs checks:
- …
=> Staging 2.26.0 ck8s5

migration/template/README.md
> [!warning]
>
> [!important]
Wanted to harmonize more with the migration doc in apps.
Context https://github.com/elastisys/welkin/pull/1142
- Fixes #
- Logs checks:
- …
=> Update Git steps in migration template README

.pre-commit-config.yaml, config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, playbooks/crds/README.md, playbooks/crds/crd-servicemonitors.yaml, playbooks/early_crds.yml
> [!warning]
>
> [!important]
Analogue of https://github.com/elastisys/ck8s-cluster-api/pull/389
Adds a playbook to install the servicemonitors CRD during `apply`, thus making sure the cilium and any other components who want to install service monitors can do so.
To test this on a new _or_ …
=> Define servicemonitors CRD early

config/common/group_vars/k8s_cluster/ck8s-k8s-cluster.yaml, migration/v2.28/README.md, migration/v2.28/prepare/20-remove-calico-version-pin.sh
Bumps `calico-accountant` from `0.1.6-ck8s2` to `0.1.6-ck8s3`.
This fixes an issue where, under Kubespray-based clusters, the
exporter could emit **duplicate metric samples with identical label sets** during
the same scrape interval.
This is linked to [this](https://github.com/elastisys/compliantkubernetes-apps/pull/2585) PR on apps
- Logs checks:
- Bug checks:
=> fix(calico): remove pinned version

config/common/group_vars/k8s_cluster/ck8s-cilium.yaml
> [!warning]
>
This enables the service monitors for Cilium by default.
These are needed for the Cilium grafana dashboards to work and so I thought it would be nice and make sense to have these enabled by default.
CAPI PR: https://github.com/elastisys/ck8s-cluster-api/pull/436
> [!important]
... …
=> config: enable cilium service monitors by default

bin/node-labels-and-taints-inventory.bash
> [!warning]
>
> [!important]
In Terraform generated inventories k8s_cluster is rendered with each host individually. However, a common use case is that a static inventory has:
[k8s_cluster:children]
kube_control_plane
kube_node
This use case was not supported.
This is now fixed by listing the …
=> List kube_control_plane + kube_node not k8s_cluster in labels and taints
